Repository pagarme/pagarme-magento, pull requests merged in 2018-08, with the labels that each got.

#326 Handle/show errors to customers
  app/code/community/PagarMe/CreditCard/Model/Creditcard.php
Labels: V2, bug

#327 Fix database migration
  app/code/community/PagarMe/Core/sql/pagarme_core_setup/mysql4-install-3.5.5.php
  app/code/community/PagarMe/Core/sql/pagarme_core_setup/mysql4-upgrade-2.0.0-3.0.0.php
Labels: V2, enhancement

#337 Implement a custom orders state/status workflow
  app/code/community/PagarMe/Boleto/etc/config.xml
  app/code/community/PagarMe/Core/Model/PostbackHandler/Authorized.php
  app/code/community/PagarMe/Core/Model/System/Config/Source/PaymentAction.php
  app/code/community/PagarMe/Core/etc/config.xml
  app/code/community/PagarMe/CreditCard/Model/Creditcard.php
  app/code/community/PagarMe/CreditCard/Model/Observers/OrderObserver.php
  app/code/community/PagarMe/CreditCard/etc/config.xml
  app/code/community/PagarMe/Modal/etc/config.xml
  app/locale/pt_BR/PagarMe_Creditcard.csv
  composer.lock
  tests/acceptance/CreditCardContext.php
  tests/acceptance/features/credit_card.feature
  tests/unit/app/code/community/PagarMe/CreditCard/Model/PagarMe_CreditCard_Model_CreditcardTest.php
Labels: V2

#338 Adjust stock for canceled orders
  app/code/community/PagarMe/Boleto/etc/config.xml
  app/code/community/PagarMe/Core/Model/OrderStatusHandler/Base.php
  app/code/community/PagarMe/Core/Model/OrderStatusHandler/Canceled.php
  app/code/community/PagarMe/Core/Model/PostbackHandler/Refused.php
  app/code/community/PagarMe/Core/etc/config.xml
  app/code/community/PagarMe/CreditCard/Model/Creditcard.php
  app/code/community/PagarMe/CreditCard/etc/config.xml
  app/code/community/PagarMe/Modal/etc/config.xml
  tests/acceptance/CreditCardContext.php
  tests/acceptance/features/credit_card.feature
Labels: V2
